server:
  port: 8080

spring:
  datasource:
    platform: h2
    #url: jdbc:h2:mem:shorturl;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    initialize: true
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console

spring.jpa:
  database: MYSQL
  showSql: true
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  properties.hibernate.hbm2ddl.auto: create-drop
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true

logging.level:
  com.papaolabs.api: DEBUG
  org.springframework: INFO
  org.hibernate: ERROR
  org.hibernate.SQL: ERROR
  org.hibernate.type.BasicTypeRegistry: WARN
